"""
Run BERT_ML OOD missing/invalid target outputs with the fewshot `llm` conda env.

Default behavior is safe:
  - Relaunches itself with C:\\Users\\HK\\miniconda3\\envs\\llm\\python.exe.
  - Detects Traditional-ML sparse/LOCO OOD target outputs.
  - Excludes HEA YS and Steel YS by default, matching the current comparison scope.
  - Dry-runs unless --execute is passed.

Typical commands from the BERT_ML repo root:

  # 1) Inspect what would be run.
  python Scripts\\run_ood_missing_with_llm_env.py --mode missing-only

  # 2) Actually backup and rerun only missing/incomplete target outputs.
  python Scripts\\run_ood_missing_with_llm_env.py --execute --mode missing-only --jobs 1

  # 3) Rerun every inconsistent BERT_ML target listed in comparison_report_v2.csv.
  python Scripts\\run_ood_missing_with_llm_env.py --execute --mode report-inconsistent --include-ys-tasks --jobs 1

  # 4) Also rerun existing sparse outputs whose split was generated by a different env.
  python Scripts\\run_ood_missing_with_llm_env.py --execute --mode all-issues --jobs 1

The script writes a manifest under:
  output\\ood_repair_backups\\llm_env_repair_YYYYMMDD_HHMMSS\\repair_manifest.json
"""

from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LLM_PYTHON = Path(r"C:\Users\HK\miniconda3\envs\llm\python.exe")

# User asked to ignore these tasks in the current comparison discussion.
DEFAULT_EXCLUDED_TARGETS = {
    ("HEA", "YS(MPa)"),
    ("Steel", "YS(MPa)"),
}

OOD_METHOD_ORDER = [
    "target_extrapolation",
    "random_cv_baseline",
    "sparse_x_single",
    "sparse_y_single",
    "sparse_x_cluster",
    "sparse_y_cluster",
    "loco",
]

ML_CONFIGS_ALL = {
    "target_extrapolation": "experiment1_all_ml_models_extrapolation",
    "random_cv_baseline": "experiment1_all_ml_models_random_cv_baseline",
    "sparse_x_single": "experiment1_all_ml_models_sparse_x_single",
    "sparse_y_single": "experiment1_all_ml_models_sparse_y_single",
    "sparse_x_cluster": "experiment1_all_ml_models_sparse_x_cluster",
    "sparse_y_cluster": "experiment1_all_ml_models_sparse_y_cluster",
    "loco": "experiment1_all_ml_models_loco",
}

ML_MODELS = ["xgboost", "sklearn_rf", "lightgbm", "mlp", "catboost"]

CASE_TO_TARGET = {
    "al_uts": ("Al", "UTS(MPa)"),
    "hea_ys": ("HEA", "YS(MPa)"),
    "hea_uts": ("HEA", "UTS(MPa)"),
    "hea_el": ("HEA", "El(%)"),
    "steel_ys": ("Steel", "YS(MPa)"),
    "steel_uts": ("Steel", "UTS(MPa)"),
    "steel_el": ("Steel", "El(%)"),
    "ti_uts": ("Ti", "UTS(MPa)"),
    "ti_el": ("Ti", "El(%)"),
    "matbench_steel_ys": ("MatbenchSteels", "yield strength"),
}


def _same_executable(left: Path, right: Path) -> bool:
    try:
        return left.resolve().samefile(right.resolve())
    except Exception:
        return str(left.resolve()).lower() == str(right.resolve()).lower()


def _read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Backup and rerun BERT_ML Traditional-ML OOD missing/invalid outputs with the llm env."
    )
    parser.add_argument(
        "--llm-python",
        type=Path,
        default=DEFAULT_LLM_PYTHON,
        help="Python executable of the target llm environment.",
    )
    parser.add_argument(
        "--no-relaunch",
        action="store_true",
        help="Do not relaunch into --llm-python. Mainly for debugging.",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually move old outputs to backup and rerun. Without this, dry-run only.",
    )
    parser.add_argument(
        "--mode",
        choices=["missing-only", "split-only", "all-issues", "report-inconsistent"],
        default="missing-only",
        help=(
            "missing-only: only missing/incomplete artifacts; "
            "split-only: only train/test split mismatches; "
            "all-issues: missing/incomplete + split mismatches + trace/model issues; "
            "report-inconsistent: rerun targets marked inconsistent in comparison_report_v2.csv."
        ),
    )
    parser.add_argument(
        "--comparison-report",
        type=Path,
        default=REPO_ROOT / "output" / "ood_dataset_compare_k5" / "comparison_report_v2.csv",
        help="Comparison CSV used by --mode report-inconsistent.",
    )
    parser.add_argument(
        "--resume-manifest",
        type=Path,
        default=None,
        help=(
            "Resume a previous repair_manifest.json by rerunning only commands whose status is not success. "
            "Already-successful commands are skipped. Existing partial output dirs for resumed tasks are moved aside."
        ),
    )
    parser.add_argument(
        "--include-value-diffs",
        action="store_true",
        help=(
            "For --mode report-inconsistent, also include rows where status is ok but value_equal is false. "
            "This is usually a Matbench source-data issue and may remain after rerun."
        ),
    )
    parser.add_argument(
        "--methods",
        nargs="+",
        default=OOD_METHOD_ORDER,
        choices=OOD_METHOD_ORDER,
        help="OOD methods to inspect/rerun.",
    )
    parser.add_argument(
        "--include-ys-tasks",
        action="store_true",
        help="Also include HEA YS(MPa) and Steel YS(MPa). They are skipped by default.",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=1,
        help=(
            "Number of target-level OOD tasks to run concurrently. "
            "Use --jobs 3 to run three independent target result directories in parallel."
        ),
    )
    parser.add_argument(
        "--verify-after",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Run post-rerun issue detection and write remaining issues to the manifest.",
    )
    return parser.parse_args()


def relaunch_with_llm_if_needed(args: argparse.Namespace) -> int | None:
    if args.no_relaunch:
        return None
    llm_python = args.llm_python
    if not llm_python.exists():
        raise FileNotFoundError(f"llm Python not found: {llm_python}")
    if _same_executable(Path(sys.executable), llm_python):
        return None

    cmd = [str(llm_python), str(Path(__file__).resolve()), *sys.argv[1:], "--no-relaunch"]
    print("[INFO] Relaunching with llm env:", flush=True)
    print("       " + " ".join(f'"{part}"' if " " in part else part for part in cmd), flush=True)
    result = subprocess.run(cmd, cwd=str(REPO_ROOT), text=True)
    return int(result.returncode)


def is_missing_reason(reason: str) -> bool:
    lowered = reason.lower()
    return (
        lowered.startswith("missing_")
        or ":missing_" in lowered
        or "missing_result_dir" in lowered
        or "missing_model_manifest" in lowered
        or "missing_model_metrics" in lowered
        or "missing_loco_manifest" in lowered
        or "missing_loco_folds" in lowered
        or "missing_trace" in lowered
        or "unreadable_trace" in lowered
    )


def is_split_reason(reason: str) -> bool:
    lowered = reason.lower()
    return (
        "id_mismatch" in lowered
        or "fold_count_mismatch" in lowered
        or "fold_index_mismatch" in lowered
        or "split_validation_error" in lowered
    )


def issue_matches_mode(issue, mode: str) -> bool:
    reasons = [str(reason) for reason in issue.reasons]
    if mode == "missing-only":
        return any(is_missing_reason(reason) for reason in reasons)
    if mode == "split-only":
        return any(is_split_reason(reason) for reason in reasons)
    return True


def load_report_task_filter(args: argparse.Namespace) -> set[tuple[str, str, str]]:
    """Return (method, alloy, target) tuples from the comparison report."""
    import pandas as pd  # Imported lazily after env relaunch.

    report_path = args.comparison_report
    if not report_path.is_absolute():
        report_path = REPO_ROOT / report_path
    if not report_path.exists():
        raise FileNotFoundError(f"comparison report not found: {report_path}")

    frame = pd.read_csv(report_path)
    required = {"method", "case", "status"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"comparison report missing columns: {sorted(missing)}")

    mask = frame["status"].astype(str).ne("ok")
    if args.include_value_diffs and "value_equal" in frame.columns:
        mask = mask | frame["value_equal"].astype(str).str.lower().eq("false")

    selected = set()
    for _, row in frame.loc[mask].iterrows():
        method = str(row["method"])
        case = str(row["case"])
        if method not in set(args.methods):
            continue
        if case not in CASE_TO_TARGET:
            print(f"[WARN] unknown case in comparison report; skipped: {case}")
            continue
        alloy, target = CASE_TO_TARGET[case]
        if not args.include_ys_tasks and (alloy, target) in DEFAULT_EXCLUDED_TARGETS:
            continue
        selected.add((method, alloy, target))
    return selected


def filter_issues(issues: Iterable, args: argparse.Namespace, report_tasks: set[tuple[str, str, str]] | None = None) -> list:
    selected = []
    method_set = set(args.methods)
    for issue in issues:
        if issue.method not in method_set:
            continue
        if not args.include_ys_tasks and (issue.alloy, issue.target) in DEFAULT_EXCLUDED_TARGETS:
            continue
        if report_tasks is not None:
            if (issue.method, issue.alloy, issue.target) not in report_tasks:
                continue
        elif not issue_matches_mode(issue, args.mode):
            continue
        selected.append(issue)
    return selected


def method_sort_index(method: str) -> int:
    try:
        return OOD_METHOD_ORDER.index(method)
    except ValueError:
        return len(OOD_METHOD_ORDER)


def clear_progress_for_selected(repair, issues: list) -> None:
    """Remove progress entries so a rerun cannot be skipped as already successful."""
    progress_file = REPO_ROOT / ".batch_progress_ood.json"
    for method in sorted({issue.method for issue in issues}, key=method_sort_index):
        config_name = ML_CONFIGS_ALL[method]
        keys = [
            repair.task_key(issue.alloy, issue.target, model)
            for issue in issues
            if issue.method == method
            for model in ML_MODELS
        ]
        repair.clear_progress_entries(progress_file, [config_name], keys)


def ml_result_dir_any(method: str, alloy: str, target: str) -> Path:
    import argparse as _argparse

    from src.pipelines.batch_configs_ood import ALLOY_CONFIGS_OOD, BATCH_CONFIGS_OOD, get_ood_method_meta
    from src.pipelines.run_batch_ood import build_result_dir

    config_name = ML_CONFIGS_ALL[method]
    cfg = BATCH_CONFIGS_OOD[config_name]
    args = _argparse.Namespace(**cfg)
    alloy_cfg = ALLOY_CONFIGS_OOD[alloy].copy()
    alloy_cfg["target_column"] = target
    return REPO_ROOT / build_result_dir(config_name, alloy, alloy_cfg, args, get_ood_method_meta(method))


def build_ml_command_any(method: str, alloy: str, target: str) -> list[str]:
    import argparse as _argparse

    from src.pipelines.batch_configs_ood import ALLOY_CONFIGS_OOD, BATCH_CONFIGS_OOD, get_ood_method_meta
    from src.pipelines.run_batch_ood import build_command

    config_name = ML_CONFIGS_ALL[method]
    cfg = BATCH_CONFIGS_OOD[config_name]
    args = _argparse.Namespace(**cfg)
    alloy_cfg = ALLOY_CONFIGS_OOD[alloy].copy()
    alloy_cfg["target_column"] = target
    return build_command(config_name, alloy, alloy_cfg, args, get_ood_method_meta(method), model_name=None)


def rerun_ml_any(repair, issues: list, execute: bool, jobs: int, backup_root: Path, manifest: dict, manifest_path: Path) -> None:
    def make_record(issue) -> dict:
        return {
            "kind": "ml_target",
            "method": issue.method,
            "alloy": issue.alloy,
            "target": issue.target,
            "models": ML_MODELS,
            "jobs_requested": jobs,
            "target_workers_requested": int(manifest.get("jobs", jobs)),
            "status": "running" if execute else "dry_run",
        }

    def command_log_for_issue(issue) -> tuple[list[str], Path]:
        cmd = build_ml_command_any(issue.method, issue.alloy, issue.target)
        log_path = (
            log_dir
            / f"{repair.safe_name(ML_CONFIGS_ALL[issue.method])}__{repair.safe_name(issue.alloy)}__{repair.safe_name(issue.target)}.log"
        )
        return cmd, log_path

    def run_one(record: dict, cmd: list[str], log_path: Path) -> dict:
        result = repair.run_command(cmd, execute=execute, log_path=log_path)
        record.update(result)
        record["status"] = "success" if result.get("returncode") == 0 else "failed"
        return record

    log_dir = backup_root / "logs" / "ml"
    sorted_issues = sorted(issues, key=lambda x: (method_sort_index(x.method), x.alloy, x.target))
    target_workers = max(1, int(manifest.get("jobs", jobs)))

    if not execute or target_workers == 1:
        for issue in sorted_issues:
            cmd, log_path = command_log_for_issue(issue)
            record = make_record(issue)
            record["log_path"] = repair.rel(log_path)
            manifest.setdefault("commands", []).append(record)
            _write_json(manifest_path, manifest)
            run_one(record, cmd, log_path)
            if execute:
                status = "success" if record.get("returncode") == 0 else "failed"
                for model in ML_MODELS:
                    repair.set_progress_entry(
                        REPO_ROOT / ".batch_progress_ood.json",
                        ML_CONFIGS_ALL[issue.method],
                        repair.task_key(issue.alloy, issue.target, model),
                        status,
                    )
            _write_json(manifest_path, manifest)
        return

    pending = []
    for issue in sorted_issues:
        cmd, log_path = command_log_for_issue(issue)
        record = make_record(issue)
        record["log_path"] = repair.rel(log_path)
        manifest.setdefault("commands", []).append(record)
        pending.append((issue, record, cmd, log_path))
    _write_json(manifest_path, manifest)

    with ThreadPoolExecutor(max_workers=target_workers) as executor:
        future_to_issue = {
            executor.submit(run_one, record, cmd, log_path): issue
            for issue, record, cmd, log_path in pending
        }
        for future in as_completed(future_to_issue):
            issue = future_to_issue[future]
            try:
                record = future.result()
            except Exception as exc:  # noqa: BLE001 - keep long batch robust.
                record = next(item[1] for item in pending if item[0] is issue)
                record["status"] = "failed"
                record["returncode"] = -1
                record["error"] = repr(exc)

            status = "success" if record.get("returncode") == 0 else "failed"
            for model in ML_MODELS:
                repair.set_progress_entry(
                    REPO_ROOT / ".batch_progress_ood.json",
                    ML_CONFIGS_ALL[issue.method],
                    repair.task_key(issue.alloy, issue.target, model),
                    status,
                )
            _write_json(manifest_path, manifest)


def synthesize_report_issues(repair, report_tasks: set[tuple[str, str, str]]) -> list:
    """Create Issue objects for report-inconsistent tasks not detected by verifier.

    Under the llm env, some old BERT_ML outputs may already match the verifier,
    but --mode report-inconsistent is intentionally driven by the comparison CSV.
    This function guarantees that every target in that report task set is backed
    up and rerun, not only the targets still detected as invalid by local checks.
    """
    issues = []
    for method, alloy, target in sorted(report_tasks, key=lambda x: (method_sort_index(x[0]), x[1], x[2])):
        issues.append(
            repair.Issue(
                "ml",
                method,
                alloy,
                target,
                ml_result_dir_any(method, alloy, target),
                ["comparison_report_inconsistent"],
            )
        )
    return issues


def load_resume_issues(repair, resume_manifest: Path) -> tuple[list, dict]:
    """Create Issue objects for non-success commands in a previous manifest."""
    manifest_path = resume_manifest if resume_manifest.is_absolute() else REPO_ROOT / resume_manifest
    if not manifest_path.exists():
        raise FileNotFoundError(f"resume manifest not found: {manifest_path}")
    payload = _read_json(manifest_path)
    commands = list(payload.get("commands") or [])
    issues = []
    skipped_success = 0
    skipped_other = 0
    seen: set[tuple[str, str, str]] = set()
    for command in commands:
        if command.get("kind") != "ml_target":
            skipped_other += 1
            continue
        if command.get("status") == "success" and command.get("returncode") == 0:
            skipped_success += 1
            continue
        method = str(command.get("method"))
        alloy = str(command.get("alloy"))
        target = str(command.get("target"))
        if method not in ML_CONFIGS_ALL or not alloy or not target:
            skipped_other += 1
            continue
        key = (method, alloy, target)
        if key in seen:
            continue
        seen.add(key)
        issues.append(
            repair.Issue(
                "ml",
                method,
                alloy,
                target,
                ml_result_dir_any(method, alloy, target),
                [f"resume_from:{manifest_path}"],
            )
        )

    report_tasks = {
        (str(item.get("method")), str(item.get("alloy")), str(item.get("target")))
        for item in payload.get("report_tasks", [])
        if item.get("method") and item.get("alloy") and item.get("target")
    }
    resume_info = {
        "resume_manifest": str(manifest_path),
        "resume_original_started_at": payload.get("started_at"),
        "resume_original_finished_at": payload.get("finished_at"),
        "resume_original_command_count": len(commands),
        "resume_skipped_success_count": skipped_success,
        "resume_skipped_other_count": skipped_other,
        "resume_selected_count": len(issues),
        "resume_report_tasks": [
            {"method": method, "alloy": alloy, "target": target}
            for method, alloy, target in sorted(report_tasks)
        ],
    }
    return sorted(issues, key=lambda x: (method_sort_index(x.method), x.alloy, x.target)), resume_info


def summarize_issues(issues: list) -> dict:
    summary: dict[str, int] = {}
    for issue in issues:
        key = f"{issue.method}|{issue.alloy}|{issue.target}"
        summary[key] = summary.get(key, 0) + 1
    return dict(sorted(summary.items()))


def main() -> int:
    args = parse_args()
    relaunched_code = relaunch_with_llm_if_needed(args)
    if relaunched_code is not None:
        return relaunched_code

    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    scripts_dir = REPO_ROOT / "Scripts"
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))

    # Import after relaunch so imported modules see sys.executable == llm python.
    import numpy as np  # noqa: WPS433
    import pandas as pd  # noqa: WPS433
    import sklearn  # noqa: WPS433
    import repair_ood_sparse_loco as repair  # noqa: WPS433

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_root = REPO_ROOT / "output" / "ood_repair_backups" / f"llm_env_repair_{timestamp}"
    manifest_path = backup_root / "repair_manifest.json"

    print(f"[INFO] repo={REPO_ROOT}")
    print(f"[INFO] python={sys.executable}")
    print(f"[INFO] sklearn={sklearn.__version__} numpy={np.__version__} pandas={pd.__version__}")
    print(f"[INFO] execute={args.execute} mode={args.mode} methods={','.join(args.methods)}")
    print(f"[INFO] backup_root={backup_root}")
    if not args.include_ys_tasks:
        print("[INFO] skipping default excluded tasks: HEA/YS(MPa), Steel/YS(MPa)")

    detected = []
    report_tasks = None
    resume_info = None
    if args.resume_manifest:
        selected, resume_info = load_resume_issues(repair, args.resume_manifest)
        report_tasks = {
            (item["method"], item["alloy"], item["target"])
            for item in resume_info.get("resume_report_tasks", [])
        } or None
        print(f"[INFO] resume_manifest={resume_info['resume_manifest']}")
        print(
            "[INFO] resume commands: "
            f"original={resume_info['resume_original_command_count']} "
            f"skipped_success={resume_info['resume_skipped_success_count']} "
            f"selected={resume_info['resume_selected_count']}"
        )
    else:
        print("[INFO] detecting Traditional-ML sparse/LOCO issues under the llm env...")
        detected = repair.detect_ml_issues()
    if not args.resume_manifest and args.mode == "report-inconsistent":
        report_tasks = load_report_task_filter(args)
        selected = synthesize_report_issues(repair, report_tasks)
        print(f"[INFO] comparison-report tasks={len(report_tasks)} from {args.comparison_report}")
    elif not args.resume_manifest:
        selected = filter_issues(detected, args)

    manifest = {
        "started_at": timestamp,
        "repo_root": str(REPO_ROOT),
        "python": sys.executable,
        "versions": {
            "sklearn": sklearn.__version__,
            "numpy": np.__version__,
            "pandas": pd.__version__,
        },
        "execute": bool(args.execute),
        "mode": args.mode,
        "methods": list(args.methods),
        "include_ys_tasks": bool(args.include_ys_tasks),
        "jobs": int(args.jobs),
        "target_workers": int(args.jobs),
        "resume": bool(args.resume_manifest),
        "resume_info": resume_info,
        "detected_issue_count": len(detected),
        "report_task_count": len(report_tasks or []),
        "report_tasks": [
            {"method": method, "alloy": alloy, "target": target}
            for method, alloy, target in sorted(report_tasks or [])
        ],
        "selected_issue_count": len(selected),
        "selected_issue_summary": summarize_issues(selected),
        "selected_issues": [repair.issue_to_dict(issue) for issue in selected],
        "backups": [],
        "commands": [],
        "post_verify_issues": [],
    }
    _write_json(manifest_path, manifest)

    print(f"[INFO] detected={len(detected)} selected={len(selected)}")
    for issue in selected[:80]:
        print(f"[ISSUE] {issue.key} -> {', '.join(issue.reasons[:5])}")
    if len(selected) > 80:
        print(f"[INFO] ... {len(selected) - 80} more selected issues")

    if not selected:
        print(f"[INFO] nothing to run. manifest={manifest_path}")
        return 0

    if not args.execute:
        print("[DRY-RUN] No files moved and no commands executed. Add --execute to actually rerun.")
        # Record the commands that would be run.
        rerun_ml_any(
            repair,
            selected,
            execute=False,
            jobs=args.jobs,
            backup_root=backup_root,
            manifest=manifest,
            manifest_path=manifest_path,
        )
        _write_json(manifest_path, manifest)
        print(f"[INFO] dry-run manifest={manifest_path}")
        return 0

    print("[INFO] backing up selected target output directories...")
    backup_root.mkdir(parents=True, exist_ok=True)
    for issue in selected:
        backup_dest = repair.backup_existing(issue.result_dir, backup_root, execute=True)
        if backup_dest:
            manifest["backups"].append(
                {
                    "kind": "ml_target",
                    "issue": repair.issue_to_dict(issue),
                    "source": repair.rel(issue.result_dir),
                    "destination": repair.rel(Path(backup_dest)),
                }
            )
            _write_json(manifest_path, manifest)

    print("[INFO] clearing progress entries for selected targets...")
    clear_progress_for_selected(repair, selected)

    print("[INFO] rerunning selected targets with llm env...")
    rerun_ml_any(
        repair,
        selected,
        execute=True,
        jobs=args.jobs,
        backup_root=backup_root,
        manifest=manifest,
        manifest_path=manifest_path,
    )

    failed_commands = [cmd for cmd in manifest.get("commands", []) if cmd.get("returncode") not in (0, None)]
    manifest["failed_commands"] = failed_commands

    if args.verify_after:
        print("[INFO] post-run verification under llm env...")
        post_detected = repair.detect_ml_issues()
        post_selected = filter_issues(post_detected, args, report_tasks=None if args.mode != "report-inconsistent" else report_tasks)
        manifest["post_verify_issues"] = [repair.issue_to_dict(issue) for issue in post_selected]
        print(f"[INFO] post_verify selected issues={len(post_selected)}")
        for issue in post_selected[:80]:
            print(f"[POST-ISSUE] {issue.key} -> {', '.join(issue.reasons[:5])}")

    manifest["finished_at"] = datetime.now().strftime("%Y%m%d_%H%M%S")
    _write_json(manifest_path, manifest)

    print(f"[INFO] manifest={manifest_path}")
    if failed_commands:
        print(f"[WARN] failed commands={len(failed_commands)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
