from __future__ import annotations

from pathlib import Path


DEFAULT_HYBRID_ROOT = Path("D:/XJTU/已完成论文数据汇总/Fewshot/预处理汇总数据/最终结果图/OOD HYBIRD/w_error_relationship")
DEFAULT_PURE_ROOT = Path("D:/XJTU/已完成论文数据汇总/Fewshot/预处理汇总数据/最终结果图/OOD/w_error_relationship")
DEFAULT_OUTPUT_DIR = Path("output") / "hybrid_method_visualizations"
DEFAULT_TRIPTYCH_ROOT = DEFAULT_HYBRID_ROOT.parent / "triptych"
SPACE_ORDER = ["X-space", "Y-space", "Z-space"]
REPRESENTATION_SPACES = ["X-space", "Z-space"]
RAW_SET_SUBSETS = ("test_extrapolation_high20", "test_inner_ood")
SUBSET_LABELS = {
    "test_extrapolation_high20": "Set A",
    "test_inner_ood": "Set B",
    "combined": "Combined",
    "test_hybrid_combined": "Combined",
}
SET_FILESYSTEM_NAMES = {"Set A": "Set_A", "Set B": "Set_B"}
RAW_SUBSET_FILESYSTEM_NAMES = {
    "test_extrapolation_high20": "Set_A",
    "test_inner_ood": "Set_B",
}
METHOD_ORDER = ["RandCV", "LOCO", "SX-sgl", "SX-cls", "SY-sgl", "SY-cls"]
MODEL_FAMILY_COLORS = {
    "Traditional": "#4c78a8",
    "BERT": "#f58518",
    "TabPFN": "#54a24b",
    "LLMProp": "#b279a2",
    "GPT": "#e45756",
}
SUBSET_MARKERS = {"Set A": "o", "Set B": "s", "Combined": "^"}
SUMMARY_COLUMNS = [
    "case",
    "task_key",
    "alloy_family",
    "dataset_name",
    "property",
    "model",
    "model_family",
    "method",
    "subset",
    "space",
    "aggregation",
    "W_mean",
    "W_median",
    "W_p90",
    "MAE",
    "RMSE",
    "R2",
    "relative_error_mean",
    "slope",
    "spearman",
    "ceiling_bias",
    "underprediction_ratio",
    "n_samples",
]
YZ_OOD_MAP_COLUMNS = [
    "case",
    "task_key",
    "alloy_family",
    "dataset_name",
    "property",
    "model",
    "model_family",
    "method",
    "subset",
    "subset_fs",
    "aggregation",
    "Wy_mean",
    "Wz_mean",
    "MAE",
    "RMSE",
    "R2",
    "relative_error_mean",
    "n_samples",
]
SET_AB_MASTER_COLUMNS = [
    "case",
    "task_key",
    "alloy_family",
    "dataset_name",
    "property",
    "model",
    "model_family",
    "method",
    "set_label",
    "subset",
    "raw_subset",
    "subset_fs",
    "aggregation",
    "fold_id",
    "ID",
    "sample_order",
    "space",
    "sample_w_contribution",
    "sample_w_mass_contribution",
    "split_w",
    "true_value",
    "predicted_value",
    "signed_error",
    "abs_error",
    "relative_error_pct",
    "prediction_file",
    "source_split_dir",
    "join_mode",
]
SET_AB_MODEL_SUMMARY_COLUMNS = [
    "case",
    "task_key",
    "alloy_family",
    "dataset_name",
    "property",
    "model",
    "model_family",
    "method",
    "set_label",
    "subset",
    "raw_subset",
    "subset_fs",
    "aggregation",
    "MAE",
    "RMSE",
    "R2",
    "relative_error_mean",
    "ceiling_bias",
    "underprediction_ratio",
    "n_samples",
    "n_folds",
    "n_ids",
    "MAE_sample",
    "MAE_source",
    "triptych_source_csv",
]
TRIPTYCH_MODEL_REVIEW_COLUMNS = [
    "case",
    "model_family",
    "model",
    "method",
    "set_label",
    "raw_subset",
    "subset_fs",
    "triptych_MAE",
    "source_csv",
]
SET_AB_FAMILY_BEST_COLUMNS = [
    "case",
    "family_label",
    "model_family",
    "method",
    "set_label",
    "raw_subset",
    "subset_fs",
    "selected_model",
    "MAE",
    "selection_rule",
    "source_csv",
]
SET_AB_AUDIT_COLUMNS = [
    "case",
    "model_family",
    "model",
    "method",
    "set_label",
    "raw_subset",
    "n_samples",
    "n_folds",
    "n_ids",
    "master_MAE_sample",
    "triptych_MAE",
    "old_summary_MAE",
    "diff_master_triptych",
    "diff_old_triptych",
    "source_csv",
    "verdict",
]
DELTA_COLUMNS = [
    "case",
    "task_key",
    "alloy_family",
    "dataset_name",
    "property",
    "model",
    "model_family",
    "method",
    "delta_MAE",
    "delta_X_W",
    "delta_Y_W",
    "delta_Z_W",
    "delta_slope_X",
    "delta_slope_Y",
    "delta_slope_Z",
    "ceiling_bias_SetA",
    "underprediction_ratio_SetA",
]
PURE_HYBRID_COLUMNS = [
    "case",
    "task_key",
    "model",
    "model_family",
    "method_group",
    "split_type",
    "subset",
    "space",
    "W_mean",
    "W_median",
    "W_p90",
    "MAE",
    "relative_error_mean",
    "n_samples",
]
MANIFEST_COLUMNS = ["scope", "task_id", "figure_id", "format", "figure"]
